// <auto-generated />
namespace Blackboard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeusers7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeusers7));
        
        string IMigrationMetadata.Id
        {
            get { return "201705061232284_removeusers7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
